# Generated by Django 6.1.1 on 2026-09-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEMP', 'Temperatura'), ('HUM', 'Humedad'), ('AMON', 'Amoníaco'), ('PESO', 'Peso')], max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
