# Generated by Django 6.1.1 on 2026-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0002_animal_delete_granja'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='saludable',
            field=models.BooleanField(default=True),
        ),
    ]
